version: "3.9"

services:
  app:
    container_name: app2
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - ./data/php/php-fpm-socket:/var/run/php-fpm
      - ./data/php/psysh:/root/.config/psysh
      - type: bind
        source: ./backend
        target: /work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-database}
      - DB_USERNAME=${DB_USER:-username}
      - DB_PASSWORD=${DB_PASS:-password}

  web:
    container_name: web2
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - ./data/php/php-fpm-socket:/var/run/php-fpm
      - type: bind
        source: ./backend
        target: /work/backend

  db:
    container_name: db2
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./data/tmp/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-database}
      - MYSQL_USER=${DB_USER:-username}
      - MYSQL_PASSWORD=${DB_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-password}

