
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
  , username     VARCHAR(60) COMMENT 'ユーザー名'
  , password     VARCHAR(31) COMMENT 'パスワード'

  , remarks    TEXT COMMENT '備考等'
  , deleted_at DATETIME(6)
  , created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
  , updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
  , is_exist   TINYINT(4) GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) VIRTUAL

  , UNIQUE(username)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'ユーザー';

