
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
  , user_id     BIGINT(20) UNSIGNED NOT NULL COMMENT 'users.id'
  , content     TEXT COMMENT '内容'

  , remarks    TEXT COMMENT '備考等'
  , deleted_at DATETIME(6)
  , created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
  , updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
  , is_exist   TINYINT(4) GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) VIRTUAL

  , FOREIGN KEY fk_posts_user_id_to_users_id (user_id)
      REFERENCES posts (id)
      ON DELETE CASCADE ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '投稿';

